"""Initial migration

Revision ID: 03d65102e447
Revises: 
Create Date: 2024-06-24 23:26:15.618886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d65102e447'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kayttajat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kayttaja', sa.String(length=80), nullable=False),
    sa.Column('salasana', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kayttaja', name=op.f('uq_kayttajat_kayttaja'))
    )
    op.create_table('kayttaja_tiedot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kayttaja_id', sa.Integer(), nullable=False),
    sa.Column('tunnus', sa.String(), nullable=False),
    sa.Column('salasana', sa.String(), nullable=False),
    sa.Column('kohde', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['kayttaja_id'], ['kayttajat.id'], name=op.f('fk_kayttaja_tiedot_kayttaja_id_kayttajat')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kayttaja_tiedot')
    op.drop_table('kayttajat')
    # ### end Alembic commands ###
